# Generated by Django 6.0.3 on 2026-08-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='b_day',
            field=models.DateField(default='2009-02-10'),
        ),
    ]
