# Generated by Django 6.0.3 on 2026-08-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_b_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default="{% static 'images/default_profile.png' %}", upload_to='profile/'),
        ),
    ]
