# Generated by Django 6.0.3 on 2026-08-17 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='')),
                ('image', models.JSONField(default=list)),
                ('video', models.JSONField(default=list)),
                ('like', models.JSONField(default=list)),
                ('message', models.CharField(default='')),
                ('share', models.JSONField(default=list)),
                ('post_type', models.CharField(default='Public')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
