# Generated by Django 6.0.3 on 2026-08-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='message',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='image',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='video',
        ),
    ]
