# Generated by Django 6.0.3 on 2026-08-18 19:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_message_posts_comment_rename_image_posts_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='post',
        ),
        migrations.AddField(
            model_name='posts',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PostsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='post/')),
                ('files_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.posts')),
            ],
        ),
    ]
